/**
 * Login user
 */

export const LOGIN = 'LOGIN'
export const AUTH_IS_LOADING = 'AUTH_IS_LOADING'
export const AUTH_STOPPED_LOADING = 'AUTH_STOPPED_LOADING'
export const ERR_LOGIN = 'ERR_LOGIN'
export const NULL_ERR_LOGIN = 'NULL_ERR_LOGIN'

/*
 * Login user
 */

export const TOKEN = 'TOKEN'
export const STORE_USER = 'STORE_USER'

/**
 * Register 
 */

export const HAS_REGISTER = 'HAS_REGISTER'
export const ERR_REGISTER = 'ERR_REGISTER'
export const NULL_ERR_REGISTER = 'NULL_ERR_REGISTER'

/**
 * Password Generator 
 */

export const GEN_PASSWORD = 'GEN_PASSWORD'

/**
 * Checklist  
 */

export const CHECKING_CHECKLIST = 'CHECKING_CHECKLIST'
export const ERR_CHECKLIST_EXIST_STATUS = 'ERR_CHECKLIST_EXIST_STATUS'
export const CHECKLIST_EXIST_STATUS = 'CHECKLIST_EXIST_STATUS'
export const NEXT_CHECKLIST = 'NEXT_CHECKLIST'

export const OPEN_DIALOG = 'OPEN_DIALOG'

export const START_STORING_CHECKLIST = 'START_STORING_CHECKLIST'
export const HAS_STORED_CHECKLIST = 'HAS_STORED_CHECKLIST'
export const STOP_STORING_CHECKLIST = 'STOP_STORING_CHECKLIST'
export const ERR_STORING_CHECKLIST = 'ERR_STORING_CHECKLIST'

/**
 * App loader
 */
export const APP_IS_LOADING = 'APP_IS_LOADING'

/**
 *  WSKPA report
 */

export const WSKPA_LOADING_STATE = 'WSKPA_LOADING_STATE'
export const FETCHED_WSKPA = 'FETCHED_WSKPA'
export const FETCHED_SINGLE_WSKPA = 'FETCHED_SINGLE_WSKPA'
export const SUCCESS_FETCHING_WSKPA = 'SUCCESS_FETCHING_WSKPA'
export const ERR_FETCHING_WSKPA = 'ERR_FETCHING_WSKPA'
export const NULL_ERR_FETCHING_WSKPA = 'NULL_ERR_FETCHING_WSKPA'
export const WSKPA_PERCENTAGE = 'WSKPA_PERCENTAGE'

/**
 *  SFCR report
 */

export const SFCR_LOADING_STATE = 'SFCR_LOADING_STATE'
export const FETCHED_SFCR_REPORT = 'FETCHED_SFCR_REPORT'
export const SFCR_SUCCESS_MESSAGE = 'SFCR_SUCCESS_MESSAGE'
export const SFCR_ERROR_MESSAGE = 'SFCR_ERROR_MESSAGE'
export const NULL_SFCR_MESSAGE = 'NULL_SFCR_MESSAGE'


/**
 * Modal Alert
 */
export const OPEN_SUCCESS_MODAL = 'OPEN_SUCCESS_MODAL'


/**
 * Chat 
 */

export const INIT_CHAT = 'INIT_CHAT'
export const FETCHING_CHATS = 'FETCHING_CHATS'
export const FETCHED_CHATS = 'FETCHED_CHATS'
export const NULL_CHAT_ERR = 'NULL_CHAT_ERR'
export const FETCHED_CHAT = 'FETCHED_CHAT'
export const CHAT_ERROR = 'CHAT_ERROR'
export const CHAT_SUCCESS = 'CHAT_SUCCESS'