export const Morning = {
    1: 'OPEN OUTLET ENTRANCE DOORS',
    2: 'STORE PADLOCKS AND KEYS AWAY FROM SIGHT',
    3: 'TAKE GEN.OUT AND CONNECT POWER CABLE',
    4: 'GAUGE FUEL AND OIL LEVEL.',
    5: 'IS THE SHOP ENVIRONMENT AND GADGETS CLEAN ? Check there is no cobwebs around',
    6: 'PUT ON INVERTER POWER SOCKET',
    7: 'PUT ON FEW FANS',
    8: 'WHEN USING GEN.',
    9: 'PAPER AVAILABILITY'

}
export const Afternoon = {
    1: 'CONFIRM DOORS ARE OPENED',
    2: 'CONFIRM FUEL LEVEL',
    3: 'CONTROL SLEEPING CUSTOMERS',
    4: 'CONTROL STAFFS WANDERING AND SLEEPING',
    5: ' AVOID SMOKING',
    6: 'LOITERING AND UNNECESSARY WHINING',
    7: 'PUT ON FEW FANS',
    8: 'WHEN USING GEN',
    9: 'PAPER AVAILABILITY',

}
export const Evening = {
    1: 'COLLATE AND RECONCILE ACCOUNT',
    2: 'SEND REPORT',
    3: 'STAFFS CLEAN UP',
    4: 'PUT OFF SYSTEMS AND INTERNET',
    5: 'PUT OFF INVERTER / UPS',
    6: 'PUT OFF AC',
    7: 'PUT CHANGE - OVER SWITCH TO MIDDLE',
    8: 'PUT OFF GEN.',
    9: 'CLOSE FUEL TAP',
    10: 'TAKE GEN INSIDE AND OTHER IMPORTANT EQUIPMENTS',
    11: ' LOCK UP ALL ENTRANCE GATES / BURGLARY TO SECURITY STANDARD',
}